/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class edu_syr_pcpratts_studio_code_jni_JniFirstExample */

#ifndef _Included_edu_syr_pcpratts_studio_code_jni_JniFirstExample
#define _Included_edu_syr_pcpratts_studio_code_jni_JniFirstExample
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     edu_syr_pcpratts_studio_code_jni_JniFirstExample
 * Method:    doPrintString
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_edu_syr_pcpratts_studio_code_jni_JniFirstExample_doPrintString
  (JNIEnv *, jobject, jstring);

#ifdef __cplusplus
}
#endif
#endif
